[package]
name = "xfs"
version = "0.2.0"
authors = ["Chris MacNaughton <chmacnaughton@gmail.com>"]
description = "A Parser for XFS performance data"
license = "MIT/Apache-2.0"

[dependencies]
nom = "~1.2"
